apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  # backend:
  #   serviceName: nginx-ingress-default-backend
  #   servicePort: 80
  tls:
    - hosts:
      - test.phuthinhtravel.vn
      secretName: default-server-secret
  rules:
  - host: test.phuthinhtravel.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http-test-svc
            port: 
              number: 80
